// Code generated by desktop/scripts/signing_identities.py go-pins; DO NOT EDIT.
// The source is desktop/signing/identities.json; keys_test.go keeps them equal.

package update

// releaseMinisignKeys are the updater's trusted minisign public keys
// (identities.json updater.minisign, primary first). With none, this build
// trusts no update signature: it reports updates and links the download page.
var releaseMinisignKeys = []string{
	"RWQYPQvwfniyo1DM1fK0WdWgblVeY1/36T4n9ETOD3FLFTzco6C6ZMcP", // primary A3B2787EF00B3D18
	"RWTolBOWK+uAuz10qcmgFOI1dSeHMhN7rvBh8K9XaB1IoATG8qQaVJ2W", // backup BB80EB2B961394E8
}

// Pinned self-signed code-signing certificates. An update must carry exactly
// these, and on macOS the same designated requirement as the running app.
const (
	releaseMacCertificateSHA1       = "32c7bb094412d12a95de7dfb5e6ed87c10348944"
	releaseMacCertificateSHA256     = "c7cbee31549b04dcac129277b1e77ff5f0c14f630c142caa5e2042d1ac581dcc"
	releaseWindowsCertificateSHA256 = "040353aabcc26f03d2f584af857d78afaf7d278ab1927f80f05b4c85eee831fa"
)
